

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_backend:
    name: build_backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./forum-backend

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with: 
        filters: |
          forum-backend:
            - 'forum-backend/**'
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.filter.outputs.forum-backend == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './forum-backend/yarn.lock'
    - name: install deps
      if: steps.filter.outputs.forum-backend == 'true'
      run: yarn install
    - name: build app
      if: steps.filter.outputs.forum-backend == 'true'
      run: NODE_ENV=production yarn build
    - name: turn on app
      if: steps.filter.outputs.forum-backend == 'true'
      run: HOST=${{ secrets.HOST }} PORT=${{ secrets.PORT }} APP_KEYS=${{ secrets.APP_KEYS }} API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} JWT_SECRET=${{ secrets.JWT_SECRET }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }} export NODE_ENV=production&&pm2 start yarn --name "backend" -- start
    
  build_frontend:
    name: build_frontend
    needs: build_backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with: 
        filters: |
          frontend:
            - 'frontend/**'
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.filter.outputs.frontend == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/yarn.lock'
    - name: install deps
      if: steps.filter.outputs.frontend == 'true'
      run: yarn install
    - name: build app
      if: steps.filter.outputs.frontend == 'true'
      run: yarn build
    - name: start app
      if: steps.filter.outputs.frontend == 'true'
      run: pm2 start yarn --name "frontend" -- start
    
